;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-delete-region
        cua-paste
        ))

(setq mc/cmds-to-run-once
      '(
        backward-char
        describe-key
        fold-dwim-toggle-all
        forward-char
        hs-toggle-hiding
        next-line
        previous-line
        seq-end
        seq-home
        ))
